### ISSUE TITLE
misp-core attempts to connect to db with wrong user

### ISSUE THREAD

**Issue by LukeVader-IV** [MISP/misp-docker#224]
**Steps to reproduce**:

- Clone repo & go to directory \*
- docker system prune --volume
- docker compose up -d
- docker compose logs --follow

**behavior**:
misp-core-1 repeatedly attempts to connect to the database "unconnected" as user "unauthenticated".
db-1 aborts connection

**Logs**:
```
misp-core-1     | 2025-02-25 14:26:31,508 WARN For [program:nginx], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
misp-core-1     | 2025-02-25 14:26:31,508 WARN For [program:php-fpm], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
misp-core-1     | 2025-02-25 14:26:31,508 WARN For [program:cron], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
misp-core-1     | 2025-02-25 14:26:31,508 INFO Included extra file "/etc/supervisor/conf.d/10-supervisor.conf" during parsing
misp-core-1     | 2025-02-25 14:26:31,508 INFO Included extra file "/etc/supervisor/conf.d/50-workers.conf" during parsing
misp-core-1     | 2025-02-25 14:26:31,508 INFO Set uid to user 0 succeeded
misp-core-1     | 2025-02-25 14:26:31,512 INFO RPC interface 'supervisor' initialized
misp-core-1     | 2025-02-25 14:26:31,900 INFO RPC interface 'supervisor' initialized
misp-core-1     | 2025-02-25 14:26:31,900 CRIT Server 'unix_http_server' running without any HTTP authentication checking
misp-core-1     | 2025-02-25 14:26:31,900 INFO supervisord started with pid 7
misp-core-1     | 2025-02-25 14:26:32,903 INFO spawned: 'cron' with pid 8
misp-core-1     | 2025-02-25 14:26:32,906 INFO spawned: 'nginx' with pid 9
misp-core-1     | 2025-02-25 14:26:32,908 INFO spawned: 'php-fpm' with pid 10
misp-core-1     | 2025-02-25 14:26:32,911 INFO spawned: 'rsyslog' with pid 12
misp-core-1     | INIT | Initialize MySQL ...
misp-core-1     | Configure PHP | Change PHP values ...
misp-core-1     | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
misp-core-1     | rsyslogd: activation of module imklog failed [v8.2302.0 try https://www.rsyslog.com/e/2145 ]
db-1            | 2025-02-25 14:26:32 65 [Warning] Aborted connection 65 to db: 'unconnected' user: 'unauthenticated' host: 'LOCALIP' (This connection closed normally without authentication)
misp-core-1     | ERROR 1130 (HY000): Host 'LOCALIP' is not allowed to connect to this MariaDB server
misp-core-1     | ... waiting for database to come up
misp-core-1     | Configure PHP | Setting 'memory_limit = 2048M'
misp-core-1     | 2025-02-25 14:26:34,877 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2025-02-25 14:26:34,877 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2025-02-25 14:26:34,877 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2025-02-25 14:26:34,877 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | Configure PHP | Setting 'max_execution_time = 300'
misp-core-1     | Configure PHP | Setting 'upload_max_filesize = 50M'
misp-core-1     | Configure PHP | Setting 'max_file_uploads = 50'
misp-core-1     | Configure PHP | Setting 'post_max_size = 50M'
misp-core-1     | Configure PHP | Setting 'max_input_time = 300'
misp-core-1     | Configure PHP | Setting 'session.save_path = 'tcp://redis:6379?auth=redispassword'
misp-core-1     | Configure PHP | Setting 'pm.max_children = 5'
misp-core-1     | Configure PHP | Setting 'pm.start_servers = 2'
misp-core-1     | Configure PHP | Setting 'pm.(min|max)_spare_servers = 2'
misp-core-1     | Configure PHP | Setting 'pm.max_requests = 0'
misp-core-1     | Configure PHP | Disabling 'pm.status_path'
misp-core-1     | Configure PHP | Disabling 'pm.status_listen'
misp-core-1     | Configure PHP | Starting PHP FPM
db-1            | 2025-02-25 14:26:37 69 [Warning] Aborted connection 69 to db: 'unconnected' user: 'unauthenticated' host: 'LOCALIP' (This connection closed normally without authentication)
misp-core-1     | ERROR 1130 (HY000): Host 'LOCALIP' is not allowed to connect to this MariaDB server
misp-core-1     | ... waiting for database to come up
db-1            | 2025-02-25 14:26:42 72 [Warning] Aborted connection 72 to db: 'unconnected' user: 'unauthenticated' host: 'LOCALIP' (This connection closed normally without authentication)
misp-core-1     | ERROR 1130 (HY000): Host 'LOCALIP' is not allowed to connect to this MariaDB server
misp-core-1     | ... waiting for database to come up
db-1            | 2025-02-25 14:26:47 75 [Warning] Aborted connection 75 to db: 'unconnected' user: 'unauthenticated' host: 'LOCALIP' (This connection closed normally without authentication)
misp-core-1     | ERROR 1130 (HY000): Host 'LOCALIP' is not allowed to connect to this MariaDB server
misp-core-1     | ... waiting for database to come up
db-1            | 2025-02-25 14:26:52 79 [Warning] Aborted connection 79 to db: 'unconnected' user: 'unauthenticated' host: 'LOCALIP' (This connection closed normally without authentication)
misp-core-1     | ERROR 1130 (HY000): Host 'LOCALIP' is not allowed to connect to this MariaDB server
```
_all LOCALIP are equal_

\* one modification was made:
the mariadb environment variables were renamed, otherwise the mariadb setup script does not function as expected, as it expects different variable names then are originally in the docker-compose.yml (I was planning on creating an MR about this)
```
environment:
    - "MARIADB_USER=${MYSQL_USER:-misp}"
    - "MARIADB_PASSWORD=${MYSQL_PASSWORD:-example}"
    - "MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}"
    - "MARIADB_DATABASE=${MYSQL_DATABASE:-misp}"
```
.env file is equal to template

**OS**: Ubuntu 24.04.2 LTS x86_64
docker was installed as per docker's official instructions
```
$ docker --version
Docker version 28.0.0, build f9ced58
```

**Comment by ostefano** [comment]
What version of the Maria DB docker image are you using?

**Comment by ostefano** [comment]
Using this https://hub.docker.com/layers/library/mariadb/10.11/images/sha256-8ad2f2b54e58d20932f3aa4a415421f676299976a527fb7d4a6470fdbb895131 and I can't reproduce.

@LukeVader-IV  Can you share your `docker-compose.yml` file?
My theory is that you are using a more recent image that broke compatibility with older ENV var names (even though that would make me suspicious).

**Comment by ostefano** [comment]
Bar any further update, I will be closing this.

**Comment by LukeVader-IV** [comment]
besides the variable names in the database, compose file is unchanged
I just did a pull so i am now on the very latest version, and the issue is still happening

```
version: '3'
services:
  # This is capable to relay via gmail, Amazon SES, or generic relays
  # See: https://hub.docker.com/r/ixdotai/smtp
  mail:
    image: ixdotai/smtp
    environment:
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"

  redis:
    image: valkey/valkey:7.2
    command: "--save '' --requirepass '${REDIS_PASSWORD:-redispassword}'"
    healthcheck:
      test: "valkey-cli -a '${REDIS_PASSWORD:-redispassword}' -p ${REDIS_PORT:-6379} ping | grep -q PONG || exit 1"
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s

  db:
    # We use MariaDB because it supports ARM and has the expected collations
    image: mariadb:10.11
    restart: always
    environment:
      - "MARIADB_USER=${MYSQL_USER:-misp}"
      - "MARIADB_PASSWORD=${MYSQL_PASSWORD:-example}"
      - "MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}"
      - "MARIADB_DATABASE=${MYSQL_DATABASE:-misp}"
    command: "\
      --innodb-buffer-pool-size=${INNODB_BUFFER_POOL_SIZE:-2048M} \
      --innodb-change-buffering=${INNODB_CHANGE_BUFFERING:-none} \
      --innodb-io-capacity=${INNODB_IO_CAPACITY:-1000} \
      --innodb-io-capacity-max=${INNODB_IO_CAPACITY_MAX:-2000} \
      --innodb-log-file-size=${INNODB_LOG_FILE_SIZE:-600M} \
      --innodb-read-io-threads=${INNODB_READ_IO_THREADS:-16} \
      --innodb-stats-persistent=${INNODB_STATS_PERSISTENT:-ON} \
      --innodb-write-io-threads=${INNODB_WRITE_IO_THREADS:-4}"
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE Prevent runaway mysql log
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD status
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 5s

  misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:${CORE_RUNNING_TAG:-latest}
    cap_add:
      - AUDIT_WRITE
    build:
      context: core/.
      args:
          - CORE_TAG=${CORE_TAG:?Missing .env file, see README.md for instructions}
          - CORE_COMMIT=${CORE_COMMIT}
          - PHP_VER=${PHP_VER:?Missing .env file, see README.md for instructions}
          - PYPI_REDIS_VERSION=${PYPI_REDIS_VERSION}
          - PYPI_LIEF_VERSION=${PYPI_LIEF_VERSION}
          - PYPI_PYDEEP2_VERSION=${PYPI_PYDEEP2_VERSION}
          - PYPI_PYTHON_MAGIC_VERSION=${PYPI_PYTHON_MAGIC_VERSION}
          - PYPI_MISP_LIB_STIX2_VERSION=${PYPI_MISP_LIB_STIX2_VERSION}
          - PYPI_MAEC_VERSION=${PYPI_MAEC_VERSION}
          - PYPI_MIXBOX_VERSION=${PYPI_MIXBOX_VERSION}
          - PYPI_CYBOX_VERSION=${PYPI_CYBOX_VERSION}
          - PYPI_PYMISP_VERSION=${PYPI_PYMISP_VERSION}
          - PYPI_MISP_STIX_VERSION=${PYPI_MISP_STIX_VERSION}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      misp-modules:
        condition: service_healthy
    healthcheck:
      test: curl -ks ${BASE_URL:-https://localhost}/users/heartbeat > /dev/null || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 30s
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files/"
      - "./ssl/:/etc/nginx/certs/"
      - "./gnupg/:/var/www/MISP/.gnupg/"
      # customize by replacing ${CUSTOM_PATH} with a path containing 'files/customize_misp.sh'
      # - "${CUSTOM_PATH}/:/custom/"
      # mount custom ca root certificates
      # - "./rootca.pem:/usr/local/share/ca-certificates/rootca.crt"
    environment:
      - "BASE_URL=${BASE_URL}"
      - "CRON_USER_ID=${CRON_USER_ID}"
      - "DISABLE_IPV6=${DISABLE_IPV6}"
      - "DISABLE_SSL_REDIRECT=${DISABLE_SSL_REDIRECT}"
      - "ENABLE_DB_SETTINGS=${ENABLE_DB_SETTINGS}"
      - "ENABLE_BACKGROUND_UPDATES=${ENABLE_BACKGROUND_UPDATES}"
      - "ENCRYPTION_KEY=${ENCRYPTION_KEY}"
      - "DISABLE_CA_REFRESH=${DISABLE_CA_REFRESH}"
      # standard settings
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "ADMIN_KEY=${ADMIN_KEY}"
      - "ADMIN_ORG=${ADMIN_ORG}"
      - "ADMIN_ORG_UUID=${ADMIN_ORG_UUID}"
      - "GPG_PASSPHRASE=${GPG_PASSPHRASE}"
      - "ATTACHMENTS_DIR=${ATTACHMENTS_DIR}"
      # OIDC authentication settings
      - "OIDC_ENABLE=${OIDC_ENABLE}"
      - "OIDC_PROVIDER_URL=${OIDC_PROVIDER_URL}"
      - "OIDC_CLIENT_ID=${OIDC_CLIENT_ID}"
      - "OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}"
      - "OIDC_ROLES_PROPERTY=${OIDC_ROLES_PROPERTY}"
      - "OIDC_ROLES_MAPPING=${OIDC_ROLES_MAPPING}"
      - "OIDC_DEFAULT_ORG=${OIDC_DEFAULT_ORG}"
      - "OIDC_LOGOUT_URL=${OIDC_LOGOUT_URL}"
      - "OIDC_SCOPES=${OIDC_SCOPES}"
      # APACHESECUREAUTH authentication settings
      - "APACHESECUREAUTH_LDAP_OLD_VAR_DETECT=${LDAP_ENABLE}"
      - "APACHESECUREAUTH_LDAP_ENABLE=${APACHESECUREAUTH_LDAP_ENABLE:-${LDAP_ENABLE}}"
      - "APACHESECUREAUTH_LDAP_APACHE_ENV=${APACHESECUREAUTH_LDAP_APACHE_ENV:-${LDAP_APACHE_ENV}}"
      - "APACHESECUREAUTH_LDAP_SERVER=${APACHESECUREAUTH_LDAP_SERVER:-${LDAP_SERVER}}"
      - "APACHESECUREAUTH_LDAP_STARTTLS=${APACHESECUREAUTH_LDAP_STARTTLS:-${LDAP_STARTTLS}}"
      - "APACHESECUREAUTH_LDAP_READER_USER=${APACHESECUREAUTH_LDAP_READER_USER:-${LDAP_READER_USER}}"
      - "APACHESECUREAUTH_LDAP_READER_PASSWORD=${APACHESECUREAUTH_LDAP_READER_PASSWORD:-${LDAP_READER_PASSWORD}}"
      - "APACHESECUREAUTH_LDAP_DN=${APACHESECUREAUTH_LDAP_DN:-${LDAP_DN}}"
      - "APACHESECUREAUTH_LDAP_SEARCH_FILTER=${APACHESECUREAUTH_LDAP_SEARCH_FILTER:-${LDAP_SEARCH_FILTER}}"
      - "APACHESECUREAUTH_LDAP_SEARCH_ATTRIBUTE=${APACHESECUREAUTH_LDAP_SEARCH_ATTRIBUTE:-${LDAP_SEARCH_ATTRIBUTE}}"
      - "APACHESECUREAUTH_LDAP_FILTER=${APACHESECUREAUTH_LDAP_FILTER:-${LDAP_FILTER}}"
      - "APACHESECUREAUTH_LDAP_DEFAULT_ROLE_ID=${APACHESECUREAUTH_LDAP_DEFAULT_ROLE_ID:-${LDAP_DEFAULT_ROLE_ID}}"
      - "APACHESECUREAUTH_LDAP_DEFAULT_ORG=${APACHESECUREAUTH_LDAP_DEFAULT_ORG:-${LDAP_DEFAULT_ORG}}"
      - "APACHESECUREAUTH_LDAP_EMAIL_FIELD=${APACHESECUREAUTH_LDAP_EMAIL_FIELD:-${LDAP_EMAIL_FIELD}}"
      - "APACHESECUREAUTH_LDAP_OPT_PROTOCOL_VERSION=${APACHESECUREAUTH_LDAP_OPT_PROTOCOL_VERSION:-${LDAP_OPT_PROTOCOL_VERSION}}"
      - "APACHESECUREAUTH_LDAP_OPT_NETWORK_TIMEOUT=${APACHESECUREAUTH_LDAP_OPT_NETWORK_TIMEOUT:-${LDAP_OPT_NETWORK_TIMEOUT}}"
      - "APACHESECUREAUTH_LDAP_OPT_REFERRALS=${APACHESECUREAUTH_LDAP_OPT_REFERRALS:-${LDAP_OPT_REFERRALS}}"
      # LdapAuth MISP authentication settings
      - "LDAPAUTH_ENABLE=${LDAPAUTH_ENABLE}"
      - "LDAPAUTH_LDAPSERVER=${LDAPAUTH_LDAPSERVER}"
      - "LDAPAUTH_LDAPDN=${LDAPAUTH_LDAPDN}"
      - "LDAPAUTH_LDAPREADERUSER=${LDAPAUTH_LDAPREADERUSER}"
      - "LDAPAUTH_LDAPREADERPASSWORD=${LDAPAUTH_LDAPREADERPASSWORD}"
      - "LDAPAUTH_LDAPSEARCHFILTER=${LDAPAUTH_LDAPSEARCHFILTER}"
      - "LDAPAUTH_LDAPSEARCHATTRIBUTE=${LDAPAUTH_LDAPSEARCHATTRIBUTE}"
      - "LDAPAUTH_LDAPEMAILFIELD=${LDAPAUTH_LDAPEMAILFIELD}"
      - "LDAPAUTH_LDAPNETWORKTIMEOUT=${LDAPAUTH_LDAPNETWORKTIMEOUT}"
      - "LDAPAUTH_LDAPPROTOCOL=${LDAPAUTH_LDAPPROTOCOL}"
      - "LDAPAUTH_LDAPALLOWREFERRALS=${LDAPAUTH_LDAPALLOWREFERRALS}"
      - "LDAPAUTH_STARTTLS=${LDAPAUTH_STARTTLS}"
      - "LDAPAUTH_MIXEDAUTH=${LDAPAUTH_MIXEDAUTH}"
      - "LDAPAUTH_LDAPDEFAULTORGID=${LDAPAUTH_LDAPDEFAULTORGID}"
      - "LDAPAUTH_LDAPDEFAULTROLEID=${LDAPAUTH_LDAPDEFAULTROLEID}"
      - "LDAPAUTH_UPDATEUSER=${LDAPAUTH_UPDATEUSER}"
      - "LDAPAUTH_DEBUG=${LDAPAUTH_DEBUG}"
      - "LDAPAUTH_LDAPTLSREQUIRECERT=${LDAPAUTH_LDAPTLSREQUIRECERT}"
      - "LDAPAUTH_LDAPTLSCUSTOMCACERT=${LDAPAUTH_LDAPTLSCUSTOMCACERT}"
      - "LDAPAUTH_LDAPTLSCRLCHECK=${LDAPAUTH_LDAPTLSCRLCHECK}"
      - "LDAPAUTH_LDAPTLSPROTOCOLMIN=${LDAPAUTH_LDAPTLSPROTOCOLMIN}"
      # AAD authentication settings
      - "AAD_ENABLE=${AAD_ENABLE}"
      - "AAD_CLIENT_ID=${AAD_CLIENT_ID}"
      - "AAD_TENANT_ID=${AAD_TENANT_ID}"
      - "AAD_CLIENT_SECRET=${AAD_CLIENT_SECRET}"
      - "AAD_REDIRECT_URI=${AAD_REDIRECT_URI}"
      - "AAD_PROVIDER=${AAD_PROVIDER}"
      - "AAD_PROVIDER_USER=${AAD_PROVIDER_USER}"
      - "AAD_MISP_USER=${AAD_MISP_USER}"
      - "AAD_MISP_ORGADMIN=${AAD_MISP_ORGADMIN}"
      - "AAD_MISP_SITEADMIN=${AAD_MISP_SITEADMIN}"
      - "AAD_CHECK_GROUPS=${AAD_CHECK_GROUPS}"
      # Nginx settings
      - "NGINX_X_FORWARDED_FOR=${NGINX_X_FORWARDED_FOR}"
      - "NGINX_SET_REAL_IP_FROM=${NGINX_SET_REAL_IP_FROM}"
      - "NGINX_CLIENT_MAX_BODY_SIZE=${NGINX_CLIENT_MAX_BODY_SIZE:-50M}"
      # Proxy settings
      - "PROXY_ENABLE=${PROXY_ENABLE}"
      - "PROXY_HOST=${PROXY_HOST}"
      - "PROXY_PORT=${PROXY_PORT}"
      - "PROXY_METHOD=${PROXY_METHOD}"
      - "PROXY_USER=${PROXY_USER}"
      - "PROXY_PASSWORD=${PROXY_PASSWORD}"
      # sync server settings (see https://www.misp-project.org/openapi/#tag/Servers for more options)
      - "SYNCSERVERS=${SYNCSERVERS}"
      - |
        SYNCSERVERS_1_DATA=
        {
          "remote_org_uuid": "${SYNCSERVERS_1_UUID}",
          "name": "${SYNCSERVERS_1_NAME}",
          "authkey": "${SYNCSERVERS_1_KEY}",
          "url": "${SYNCSERVERS_1_URL}",
          "pull_rules": "${SYNCSERVERS_1_PULL_RULES}",
          "pull": true
        }
      # mysql settings
      - "MYSQL_HOST=${MYSQL_HOST:-db}"
      - "MYSQL_PORT=${MYSQL_PORT:-3306}"
      - "MYSQL_USER=${MYSQL_USER:-misp}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-misp}"
      # redis settings
      - "REDIS_HOST=${REDIS_HOST:-redis}"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}"
      # Debug setting
      - "DEBUG=${DEBUG}"
      # SMTP setting
      - "SMTP_FQDN=${SMTP_FQDN}"
      # NGINX settings
      - "FASTCGI_READ_TIMEOUT=${FASTCGI_READ_TIMEOUT:-300s}"
      - "FASTCGI_SEND_TIMEOUT=${FASTCGI_SEND_TIMEOUT:-300s}"
      - "FASTCGI_CONNECT_TIMEOUT=${FASTCGI_CONNECT_TIMEOUT:-300s}"
      - "FASTCGI_STATUS_LISTEN=${FASTCGI_STATUS_LISTEN}"
      # PHP settings
      - "PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}"
      - "PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-300}"
      - "PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-50M}"
      - "PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-50M}"
      - "PHP_MAX_INPUT_TIME:${PHP_MAX_INPUT_TIME:-300}"
      - "PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS:-50}"
      # PHP FPM pool setup
      - "PHP_FCGI_CHILDREN=${PHP_FCGI_CHILDREN:-5}"
      - "PHP_FCGI_START_SERVERS=${PHP_FCGI_START_SERVERS:-2}"
      - "PHP_FCGI_SPARE_SERVERS=${PHP_FCGI_SPARE_SERVERS:-1}"
      - "PHP_FCGI_MAX_REQUESTS=${PHP_FCGI_MAX_REQUESTS:-0}"
      # Additional PHP settings
      - "PHP_SESSION_TIMEOUT=${PHP_SESSION_TIMEOUT:-60}"
      - "PHP_SESSION_COOKIE_TIMEOUT=${PHP_SESSION_COOKIE_TIMEOUT:-10080}"
      - "PHP_SESSION_DEFAULTS=${PHP_SESSION_DEFAULTS:-php}"
      - "PHP_SESSION_AUTO_REGENERATE=${PHP_SESSION_AUTO_REGENERATE:-false}"
      - "PHP_SESSION_CHECK_AGENT=${PHP_SESSION_CHECK_AGENT:-false}"
      - "PHP_SESSION_COOKIE_SECURE=${PHP_SESSION_COOKIE_SECURE:-true}"
      - "PHP_SESSION_COOKIE_DOMAIN=${PHP_SESSION_COOKIE_DOMAIN}"
      - "PHP_SESSION_COOKIE_SAMESITE=${PHP_SESSION_COOKIE_SAMESITE:-Lax}"
      # Security Settings
      - "HSTS_MAX_AGE=${HSTS_MAX_AGE}"
      - "X_FRAME_OPTIONS=${X_FRAME_OPTIONS}"
      - "CONTENT_SECURITY_POLICY=${CONTENT_SECURITY_POLICY}"

  misp-modules:
    image: ghcr.io/misp/misp-docker/misp-modules:${MODULES_RUNNING_TAG:-latest}
    build:
      context: modules/.
      args:
        - MODULES_TAG=${MODULES_TAG:?Missing .env file, see README.md for instructions}
        - MODULES_COMMIT=${MODULES_COMMIT}
        - LIBFAUP_COMMIT=${LIBFAUP_COMMIT:?Missing .env file, see README.md for instructions}
    environment:
      - "REDIS_BACKEND=${REDIS_HOST:-redis}"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PW=${REDIS_PASSWORD:-redispassword}"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: "/bin/bash -c '</dev/tcp/localhost/6666'"
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s

volumes:
    mysql_data:
```

**Comment by ostefano** [comment]
@LukeVader-IV start from scratch WITHOUT changing the env variable names, and post the error.

That is the error I want to see.

**Comment by LukeVader-IV** [comment]
Right, this will recreate the issue i already solved. Starting completely from scratch, only the logs of the db:
```
db-1            | 2025-02-25 15:55:29+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.11+maria~ubu2204 started.
db-1            | 2025-02-25 15:55:30+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB
db-1            | 2025-02-25 15:55:30+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-1            | 2025-02-25 15:55:30+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.11+maria~ubu2204 started.
db-1            | 2025-02-25 15:55:32+00:00 [Note] [Entrypoint]: MariaDB upgrade information missing, assuming required
db-1            | 2025-02-25 15:55:32+00:00 [Note] [Entrypoint]: MariaDB upgrade (mariadb-upgrade or creating healthcheck users) required, but skipped due to $MARIADB_AUTO_UPGRADE setting
db-1            | 2025-02-25 15:55:32 0 [Note] Starting MariaDB 10.11.11-MariaDB-ubu2204 source revision e69f8cae1a15e15b9e4f5e0f8497e1f17bdc81a4 server_uid 15N9Un+d4unO54phGv4EWq0hcR0= as process 1
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Number of transaction pools: 1
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
db-1            | 2025-02-25 15:55:33 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
db-1            | 2025-02-25 15:55:33 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 1
db-1            | 2025-02-25 15:55:33 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Initializing buffer pool, total size = 2.000GiB, chunk size = 32.000MiB
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Completed initialization of buffer pool
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: End of log at LSN=47012
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: 128 rollback segments are active.
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: log sequence number 47012; transaction id 14
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db-1            | 2025-02-25 15:55:33 0 [Note] Plugin 'FEEDBACK' is disabled.
db-1            | 2025-02-25 15:55:33 0 [Note] InnoDB: Buffer pool(s) load completed at 250225 15:55:33
db-1            | 2025-02-25 15:55:34 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
db-1            | 2025-02-25 15:55:34 0 [Note] Server socket created on IP: '0.0.0.0'.
db-1            | 2025-02-25 15:55:34 0 [Note] Server socket created on IP: '::'.
db-1            | 2025-02-25 15:55:36 0 [Note] mariadbd: ready for connections.
db-1            | Version: '10.11.11-MariaDB-ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
db-1            | 2025-02-25 15:55:36 3 [Warning] Access denied for user 'misp'@'localhost' (using password: YES)
db-1            | 2025-02-25 15:55:41 4 [Warning] Access denied for user 'misp'@'localhost' (using password: YES)
db-1            | 2025-02-25 15:55:46 5 [Warning] Access denied for user 'misp'@'localhost' (using password: YES)
db-1            | 2025-02-25 15:55:51 6 [Warning] Access denied for user 'misp'@'localhost' (using password: YES)
db-1            | 2025-02-25 15:55:53 7 [Warning] Access denied for user 'misp'@'localhost' (using password: YES)
```

as you can see, the user does not get created, and the healthcheck keeps trying to connect to a non-existent user.
I have already found out that in the initialisation, *only* MARIADB_... get used and not MYSQL_....

**Comment by LukeVader-IV** [comment]
Inside of the mariadb container in /usr/local/bin/docker-entrypoint.sh in the function docker_setup_db()

```
...
if  [ -n "$MARIADB_PASSWORD" ] || [ -n "$MARIADB_PASSWORD_HASH" ] && [ -n "$MARIADB_USER" ]; then
  mysql_note "Creating user ${MARIADB_USER}"
  if [ -n "$MARIADB_PASSWORD_HASH" ]; then
    createUser="CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY PASSWORD '$MARIADB_PASSWORD_HASH';"
  else
    # SQL escape the user password, \ followed by '
    local userPasswordEscaped
    userPasswordEscaped=$(docker_sql_escape_string_literal "${MARIADB_PASSWORD}")
    createUser="CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$userPasswordEscaped';"
  fi

  if [ -n "$MARIADB_DATABASE" ]; then
    mysql_note "Giving user ${MARIADB_USER} access to schema ${MARIADB_DATABASE}"
    userGrants="GRANT ALL ON \`${MARIADB_DATABASE//_/\\_}\`.* TO '$MARIADB_USER'@'%';"
  fi
fi
...
```

As you can see, it requires a $MARIADB_USER, not a $MYSQL_USER
Granted, i have not checked everything, but this to me indicated that no MYSQL variables are used
This can be confirmed by the fact that changing the variable names fixes this issue

**Comment by ostefano** [comment]
@LukeVader-IV sure but

```
# set MARIADB_xyz from MYSQL_xyz when MARIADB_xyz is unset
# and make them the same value (so user scripts can use either)
_mariadb_file_env() {
	local var="$1"; shift
	local maria="MARIADB_${var#MYSQL_}"
	file_env "$var" "$@"
	file_env "$maria" "${!var}"
	if [ "${!maria:-}" ]; then
		export "$var"="${!maria}"
	fi
}
```

Please remove the volume and try again.

**Comment by ostefano** [comment]
When I say remove the volume I mean "docker volume rm <ID>" where ID is the volume you MISP volume you get from "docker volume ls".

@LukeVader-IV  I am closing this now.

**Comment by LukeVader-IV** [comment]
The issue was solved now, I assume that there was some change in the mariadb container, as i pulled a newer version yesterday, and I possibly didn't remove the docker volume as i believed i had.
Thank you for the help.

**Comment by mahesar-instiki** [comment]
I'm still having the same issue, is there any solutions that i should need to do?, i'm installing with Wazuh, IRIS-DFIR, Shuffle, and lastly MISP

[file.txt](https://github.com/user-attachments/files/24448259/file.txt)
